[pytest]
DJANGO_SETTINGS_MODULE = oc_lettings_site.settings
python_files = tests.py test_*.py *_tests.py
addopts = --cov=lettings --cov=profiles --cov=oc_lettings_site --cov-report=term-missing --cov-fail-under=80
