# Generated by Django 3.0 on 2024-11-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Supprimer `Profile` de l'état Django
                migrations.RemoveField(
                    model_name='profile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Profile',
                ),
                # Supprimer `Letting` de l'état Django
                migrations.DeleteModel(
                    name='Letting',
                ),
            ],
            database_operations=[
                # Ne rien faire sur la base de données
            ],
        ),
    ]
